apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: content-tag-deployment
  namespace: ingress-nginx
  labels:
    app: content-tag
spec:
  replicas: 2
  selector:
    matchLabels:
      app: content-tag
  template:
    metadata:
      labels:
        app: content-tag
    spec:
      containers:
      - name: content-tag
        image: xiaoice.azurecr.io/corechat/content-tagging:v1.1.17
        ports:
        - containerPort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: content-tag-service
  namespace: ingress-nginx
spec:
  selector:
    app: content-tag
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80